### ISSUE TITLE
thoughts on reading NIX_LD and NIX_LD_LIBRARY_PATH from configuration file?

### ISSUE THREAD

**Issue by contrun** [nix-community/nix-ld#17]
I find building fuchsia difficult because fuchsia's build script runs `env --ignore-environment`. My manually-set environment variable`NIX_LD` is thus unset. If `nix-ld` is to read the interpreter from some configuration file, then I can run fuchsia's pre-built binaries. What is your opinion of adding configuration file support?

**Comment by Mic92** [comment]
I think that should be fine, but if either `NIX_LD` or `NIX_LD_LIBRARY_PATH` is set, this should be preferred.

**Comment by Mic92** [comment]
I encountered the same issue with bazel and already put some though into it. I think as a first solution I would add a global `/etc/nix-ld.conf` that just contains the following:

```
NIX_LD=/nix/store/...ld.so
NIX_LD_LIBRARY_PATH=/run/current-system/sw/share/nix-ld/lib
```

Per project devshell configurations are a bit more trickier because just loading random files from a repository can lead to security issue i.e. one person downloads an untrusted repository and than tries to edit it with vscode which has unpatched binaries. I think what can help here if we instead place configurations into
`$HOME/.data/nix-ld/trusted/<hash-of-the-directory>` (or inside `$XDG_DATA_HOME/nix-ld/trusted` if set). This directory can be than populated from `shellHook` within nix-shell for example or some other shell wrapper for the project.

Both solutions are not super hard to implement if you have some C knowledge except for the fact that we do not have full libc in nix-ld. Instead nix-ld uses the nolibc project from the linux kernel as it needs to be compiled in a single compilation unit (link-loader are a bit special).

Another solution would be to just default to `/run/current-system/sw/share/nix-ld/lib` and `/run/current-system/sw/share/nix-ld/ld.so` if no configuration exists.

**Comment by Mic92** [comment]
So far vscode WSL seems to work with nix-ld installed. When vscode logs in with ssh it will get the environment variables for nix-ld set by PAM. That worked reliable in our setup.

**Comment by Mic92** [comment]
I had to undo this again because it would not correctly insert LD_LIBRARY_PATH: https://github.com/Mic92/nix-ld/pull/58

**Comment by avakhrenev** [comment]
I also use `nix-ld` with bazel, which clears env variables. In my case, an acceptable solution is to patch it on my machine:
```patch
   if (!ctx.nix_ld) {
-    log_error(&ctx, "You are trying to run an unpatched binary on nixos, but you have not configured NIX_LD or NIX_LD_" NIX_SYSTEM ". See https://github.com/Mic92/nix-ld for more details");
-    return 1;
+    ctx.nix_ld = "@dynamicLinkerPath@";
   }
```
in the NixOS configuration overlay:
```nix
final: prev: {
  nix-ld = prev.nix-ld.overrideAttrs (f: p: {
    patches = [
      (pkgs.runCommand "nix-ld.patch" {} ''
        export nixldso=$(cat '${pkgs.stdenv.cc}/nix-support/dynamic-linker')
        substituteAll ${./nix-ld.patch} $out
      '')
    ];
  });
}
```
Build times are negligible (compared to, say, nvidia drivers). If it would be packaged the same way in `nixpkgs`, it would be built by hydra with the correct dynamic linker.

**Comment by K900** [comment]
You might be interested in https://github.com/nix-community/nix-ld-rs/ , which implements the fallback behavior correctly.

**Comment by Mic92** [comment]
> I also use `nix-ld` with bazel, which clears env variables. In my case, an acceptable solution is to patch it on my machine:
> 
> ```diff
>    if (!ctx.nix_ld) {
> -    log_error(&ctx, "You are trying to run an unpatched binary on nixos, but you have not configured NIX_LD or NIX_LD_" NIX_SYSTEM ". See https://github.com/Mic92/nix-ld for more details");
> -    return 1;
> +    ctx.nix_ld = "@dynamicLinkerPath@";

You will run into issues with this approach if your NIX_LD_LIBRARY_PATH uses libraries linked against a different version of glibc compared to the dynamic loader (which will load it's own libc). That's why it is usually recommend to set both at the same time. I'd also recommend to test if nix-ld-rs fixes your issue as this is the solution I want to make the default for nix-ld after some testing.

**Comment by Mic92** [comment]
nix ld now fallback to the system path since nix-ld 2.0.
It will use /run/current-system/sw/share/nix-ld/lib/ld.so
and /run/current-system/sw/share/nix-ld/lib
by default.
I think this implemented the intended effect here.
